### ISSUE TITLE
Vertical Mode 时的滑动感知阈值问题

### ISSUE THREAD

**Issue by 29995270** [alibaba/UltraViewPager#1]
关于垂直滑动的实现，应该是跟下面这个库完全相同
https://github.com/kaelaela/VerticalViewPager
但是这种实现有个很明显的问题，就是在转换坐标后并没有很好的处理滑动在 水平和 垂直上的判断比例，
造成 不那么标准的垂直滑动 会无法触发 ViewPager的滑动。
setPageMargin 也会因为宽高比的翻转而得不到想要的 margin。

**Comment by MikeAfc** [comment]
嗯，这个确实是受实现的限制，正在考虑更好的实现方式
