### ISSUE TITLE
PageMargin?

### ISSUE THREAD

**Issue by uzman** [alibaba/UltraViewPager#10]
hi,
i couldn't  find the pageMargin method.
i want to put spacing between pages in vertical/horizontal mode.

is it possible to use setMultiScreen with page margin in both ways (vertical, horizontal)?

**Comment by MikeAfc** [comment]
You can invoke mUltraViewPager.getViewPager() to get actual ViewPager, and to set pageMargin invoke mUltraViewPager.getViewPager().setPageMargin().

**Comment by uzman** [comment]
hi
i tried it in your sample, but it makes the view pager default appearance. 
it just sets the view pager margin. multiscreen doesn't run.

            case 3:
            case 5:
            case 6:
                ultraViewPager.setScrollMode(UltraViewPager.ScrollMode.HORIZONTAL);
                adapter = new UltraPagerAdapter(true);
                ultraViewPager.setAdapter(adapter);
                ultraViewPager.setMultiScreen(0.6f);
                ultraViewPager.setItemRatio(1.0f);
                ultraViewPager.getViewPager().setPageMargin(20);
