### ISSUE TITLE
请问一下，如何正常显示圆角

### ISSUE THREAD

**Issue by SunxiaoyaoHHL** [alibaba/UltraViewPager#101]
设置了圆角，只要滑动就会变成直角

**Comment by MikeAfc** [comment]
麻烦再多提供一些信息

**Comment by SunxiaoyaoHHL** [comment]
用作banner，设置了viewpager以及图片的background圆角，滑动下一页过程中会变成直角

**Comment by gp888** [comment]
用CardView包一下？
<android.support.v7.widget.CardView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        app:cardCornerRadius="@dimen/dimens_5"
        app:cardUseCompatPadding="false"
        app:cardElevation="0px"
        android:layout_marginStart="@dimen/dimens_12"
        android:layout_marginEnd="@dimen/dimens_12">

        <com.tmall.ultraviewpager.UltraViewPager
            android:id="@+id/ultra_viewpager"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_constraintTop_toTopOf="parent" />

    </android.support.v7.widget.CardView>
