### ISSUE TITLE
Error on adapter update

### ISSUE THREAD

**Issue by af-kabramov** [alibaba/UltraViewPager#16]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 4 Pager id: ffffffff Pager class: class com.tmall.ultraviewpager.UltraViewPagerView Problematic adapter: class com.tmall.ultraviewpager.UltraViewPagerAdapter

i'd updated adapter just a simple 
![image](https://cloud.githubusercontent.com/assets/9871300/25519886/5cf431b6-2c02-11e7-9c2d-39801477fc33.png)

**Comment by hanyulin1314** [comment]
you can do it just add ' mUltraViewpager.getViewPager().getAdapter().notifyDataSetChanged();'
