### ISSUE TITLE
设置item之间距离无效

### ISSUE THREAD

**Issue by qinyang1018** [alibaba/UltraViewPager#19]
设置item之间的距离是否是用下图的属性，设置后无效
![image](https://cloud.githubusercontent.com/assets/15726024/25689903/8120d632-30be-11e7-8077-91876325504b.png)
![image](https://cloud.githubusercontent.com/assets/15726024/25689908/8e301c48-30be-11e7-8582-0df32e5f77ee.png)

建议api文档写的详细点，现在好多属性都要挨个试验才能知道具体功能

**Comment by MikeAfc** [comment]
感谢建议，文档会持续补充。
https://github.com/alibaba/UltraViewPager/commit/c241c629ff2263c6446c7e2a27cd0bd22ad99e10

更新下1.0.4版本，新增了 setHGap 接口供设置两页之间的间距，参数为像素

**Comment by qinyang1018** [comment]
非常感谢
