### ISSUE TITLE
Resource not found exception

### ISSUE THREAD

**Issue by shreyanshjain1991** [alibaba/UltraViewPager#21]
android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff

**Comment by MikeAfc** [comment]
This may offer some help： [http://stackoverflow.com/questions/22578262/what-is-wrong-with-this-code-to-use-a-viewpager](http://stackoverflow.com/questions/22578262/what-is-wrong-with-this-code-to-use-a-viewpager)

**Comment by MikeAfc** [comment]
#12
