### ISSUE TITLE
当fragment数量在3个及以下是会报错，但4个及以上就OK，请问这个怎么解决？

### ISSUE THREAD

**Issue by caiyani** [alibaba/UltraViewPager#30]
当fragment为2个时会出现Fragment already added: twofragment{41ac1a78 #1 id=0x1 android:switcher:1:1}；为3个时可以运行，但向前滑动fragment加载不出来。但是4个及以上的时候使用正常，请问这个问题该怎么解决？

**Comment by liihuu** [comment]
@caiyani 请问这个问题你解决了么？解决方法是啥？
