### ISSUE TITLE
更新问题+崩溃(bug)

### ISSUE THREAD

**Issue by MinchinWang** [alibaba/UltraViewPager#34]
demo项目依赖
    compile 'com.android.support:appcompat-v7:25.3.1'
继承AppCompatActivity
notifyDataSetChanged();无效

去掉依赖
    compile 'com.android.support:appcompat-v7:25.3.1'
继承AppCompatActivity
notifyDataSetChanged();有效

**Comment by MrTaohf** [comment]
mViewPager.getViewPager().getAdapter().notifyDataSetChanged(); 完美解决 别使用自己的PagerAdapter刷新数据

**Comment by MikeAfc** [comment]
Have added method to help refresh data. See faq to learn more:
https://github.com/alibaba/UltraViewPager/wiki/FAQ
https://github.com/alibaba/UltraViewPager#faq
