### ISSUE TITLE
数据更新后，调用notifyDataSetChanged无效并且异常退出

### ISSUE THREAD

**Issue by zhangxiliang** [alibaba/UltraViewPager#36]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 1200 Pager id: 1 Pager class: class com.tmall.ultraviewpager.UltraViewPagerView Problematic adapter: class com.tmall.ultraviewpager.UltraViewPagerAdapter
                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1167)
                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:622)
                                                                     at com.tmall.ultraviewpager.UltraViewPagerView.setCurrentItemFake(UltraViewPagerView.java:235)
                                                                     at com.tmall.ultraviewpager.UltraViewPager.scrollNextPage(UltraViewPager.java:360)
                                                                     at com.tmall.ultraviewpager.UltraViewPager$2.callBack(UltraViewPager.java:293)
                                                                     at com.tmall.ultraviewpager.TimerHandler.handleMessage(TimerHandler.java:55)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                     at android.os.Looper.loop(Looper.java:207)

 compileSdkVersion 25
 buildToolsVersion "25.0.2"

**Comment by ostea** [comment]
我也遇到了这个问题，你是怎么解决的呢。

**Comment by pdog18** [comment]
原因是外面包裹的`UltraViewPagerAdapter`，重写的`getCount()`
有个if导致返回的count *400 ，但是此时数据更新的`dataSetChanged` 还没有被调用， `mExpectedAdapterCount` 也没有被复制
所以发生了`N != mExpectedAdapterCount` 

```

    private void defaultUltraViewPager() {
        UltraViewPager ultraViewPager = (UltraViewPager) findViewById(R.id.ultra_viewpager);
        ultraViewPager.setScrollMode(UltraViewPager.ScrollMode.HORIZONTAL);
        //initialize UltraPagerAdapter，and add child view to UltraViewPager
        final UltraPagerAdapter adapter = new UltraPagerAdapter(false);
        ultraViewPager.setAdapter(adapter);

        final List<String> strings = new ArrayList<>();
        for (int i = 0; i < 8; i++) {
            strings.add(i + "");
        }

        adapter.setData(strings);


        //set an infinite loop
        ultraViewPager.setInfiniteLoop(true);
//        enable auto-scroll mode
        ultraViewPager.setAutoScroll(2000);

        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                List<String> stringList = new ArrayList<String>();

                for (int i = 0; i < 15; i++) {
                    stringList.add(i + "plus");
                }
                adapter.setData(stringList);
                adapter.notifyDataSetChanged();
            }
        }, 5000);       //5000ms后crash
        /**
         * Java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 4000, found: 2000 Pager id: 1 Pager class: class com.tmall.ultraviewpager.UltraViewPagerView Problematic adapter: class com.tmall.ultraviewpager.UltraViewPagerAdapter
         at android.support.v4.view.ViewPager.populate(ViewPager.java:1167)
         */

    }
```
@MikeAfc 请求修复这个问题

**Comment by pdog18** [comment]
在UltraViewPager.java 中
```
    @Override
    public void scrollNextPage() {
        viewPager.getAdapter().notifyDataSetChanged();
        if (viewPager != null && viewPager.getAdapter() != null && viewPager.getAdapter().getCount() > 0) {
            final int curr = viewPager.getCurrentItemFake();
            int nextPage = 0;
            if (curr < viewPager.getAdapter().getCount() - 1) {
                nextPage = curr + 1;
            }
            viewPager.setCurrentItemFake(nextPage, true);
        }
    }
```

我在`scrollNextPage()`方法中刷新一下数据，这样就不会产生了`N != mExpectedAdapterCount` 了。

**Comment by hongming1218** [comment]
@pdog18   那如何正确添加数据源呢

**Comment by liaoinstan** [comment]
我也遇到这个问题了，修改数据源后，notifyDataSetChanged();确实会抛出异常，前提是修改了数据源的size，修改内容没问题

**Comment by ZQ7** [comment]
这个Bug什么时候可以修复。。。。 @MikeAfc

**Comment by imliujun** [comment]
@MikeAfc 同问，这个Bug太严重了

**Comment by typhoon322** [comment]
遇到同样的情况，数据回来之后根本没法更新。

**Comment by z2700589** [comment]
同样的问题，现在这个bug修复了吗？

**Comment by MrTaohf** [comment]
这个问题被修复了吗？？？

**Comment by a512509050** [comment]
结合vlayout使用应该怎么处理这么bug呢
```
@Override
            public void onBindViewHolder(ViewHolder holder, int position) {
                UltraViewPager viewPager = holder.itemView.findViewById(R.id.uvp_notice);
                if (viewPager != null) {
                    viewPager.setScrollMode(UltraViewPager.ScrollMode.VERTICAL);

                    viewPager.setInfiniteLoop(true);
                    viewPager.setAutoScroll(2000);

                    NoticePagerAdapter pagerAdapter = new NoticePagerAdapter(getContext(), this, viewPool, mNoticeList);
                    pagerAdapter.setOnItemClickListener((view, position1) ->
                            Toast.makeText(getContext(), "position:" + position1, Toast.LENGTH_SHORT).show());
                    viewPager.setAdapter(pagerAdapter);
                }
            }
```

**Comment by luoxiong94** [comment]
mViewPager.getViewPager().getAdapter().notifyDataSetChanged(); 完美解决 别使用自己的PagerAdapter刷新数据 ，正解！！！

**Comment by MikeAfc** [comment]
Have added method to help refresh data. See faq to learn more:
https://github.com/alibaba/UltraViewPager/wiki/FAQ
https://github.com/alibaba/UltraViewPager#faq
