### ISSUE TITLE
关于无限循环问题

### ISSUE THREAD

**Issue by zouzhenglu** [alibaba/UltraViewPager#4]
设置无限循环的时候，代码写死了getCount * 4 是什么意思？
当循环完后，又会跑到第一张，这时候有个动画。有没有办法可以不要动画？
我设置了setCurrentItem后回到了第一张，但是，在UltraScaleTransformer的模式下有个问题，中间的item跟左边的item粘一起，没用间距了。有没有什么好的方案可以实现无限循环问题呢

**Comment by 1181631922** [comment]
因为作者的源码设置了最大值时你的list的4倍（INFINITE_RATIO），你可以查看一下源码
`@Override
    public int getCount() {
        int count;
        if (enableLoop) {
            if (adapter.getCount() == 0) {
                count = 0;
            } else {
                count = adapter.getCount() *INFINITE_RATIO;
            }
        } else {
            count = adapter.getCount();
        }
        return count;
    }`
如果你想循环多次的话可以加个大点的数，一般用户不会滑动那么多的，但是治标不治本，希望你自己看一下源码

**Comment by MikeAfc** [comment]
先从无限循环的实现方式说起：
* 比较 trick 一点的方案：直接把 ViewPager 的 Adapter 里的 items 数量直接放大到无限 (一般是int 的最大值)，这样看起来和体验起来都会是无限，实现成本较低，不需要修改 ViewPager 源码；
* 真正意义上的无限循环：拉一份 ViewPager 源码，直接修改populate方法里判断左右滑动的实现，尝试过这个方案，体验上目前还做不到完美无限循环，最后一帧到第一帧会有一个跳的动画；这个方案的另一个问题是当 ViewPager 源码有大更新的时候，你的 library 也必须随着改一次，存在维护成本；

说回 UltraViewPager 的实现，为什么这里有一个看起来是 magic number 的值，是因为当 items 的数量放大到一定程度后，对性能是有损耗的，损耗多少取决于内部 View 的绘制复杂程度和放大的倍数，为什么这么说，原因也在 ViewPager 的 populate 方法里，看源码可以看到 populate方法里有几个 for 循环在循环所有 items；

所以 UltraViewPager 对这个放大的倍数取了一个很小的值，目的是以最小的损耗让大多数用户看起来这个 ViewPager 是无限的，不过这个值确实不应该写死，后面会提供接口修改，让大家设置自己合适的值。

**Comment by zouzhenglu** [comment]
目前是直接修改了源码，暴露了一个方法，然后我再在pager加监听，在置顶位置的时候移动，现在是看不到有跳一下的情况，所以算是解决了现在的问题。thx
