### ISSUE TITLE
Bitmap Images doesn't show

### ISSUE THREAD

**Issue by vivek50** [alibaba/UltraViewPager#42]
When i load bitmap images , it doesn't show me result..
but when i use normal image it shows perfectly..
Actually, problem is pager takes lots of memory..of my phone..
so what i do??

**Comment by MikeAfc** [comment]
You can invoke `com.tmall.ultraviewpager.UltraViewPagerAdapter#setInfiniteRatio`, and set infinite ratio to a small value.
