### ISSUE TITLE
viewpager显示bug

### ISSUE THREAD

**Issue by 1181631922** [alibaba/UltraViewPager#53]
![7379b69d-27d0-42b1-b181-d7d99644558a](https://user-images.githubusercontent.com/10703705/30109748-13a14ed2-933a-11e7-8d61-e1c92e201aac.png)

会把下一屏的一部分显示到这一屏上
setPageMargin((int) (-(pageMargin + convertDp2Px(getContext(), 1f))));
为什么右侧有个1f的margin？

**Comment by MikeAfc** [comment]
Fixed in version 1.0.6.1
