### ISSUE TITLE
某些机型会报bug，我的是mate9

### ISSUE THREAD

**Issue by 1181631922** [alibaba/UltraViewPager#54]
![image](https://user-images.githubusercontent.com/10703705/30238079-71e6bede-9572-11e7-823d-3b08fea1d957.png)

ULtraViewPagerView.java这个onmeasure方法，没有判空的话会报bug，我只是加了一个判断，不知道会不会引起别的问题，博主可以看下

**Comment by MikeAfc** [comment]
和 #79 一并修复
