### ISSUE TITLE
测试demo无法实现一屏多显

### ISSUE THREAD

**Issue by W2L** [alibaba/UltraViewPager#57]
未改动代码，直接点击MultiScreen_V后进入，为看到一屏多显示的效果

**Comment by zp-huang** [comment]
![image](https://user-images.githubusercontent.com/7100670/30799644-1c86e158-a210-11e7-8e8b-aa7ba3b835e9.png)
MultiScreen_H点进去只看到一个显示缩小之后的View

**Comment by shenshuo** [comment]
我也是 我手里的demo  有两个不是 无法无限轮播 就是 显示不了 多个

**Comment by xingshijie** [comment]
@shenshuo @zp-huang #65 这个里面有答案

**Comment by MikeAfc** [comment]
Fixed on version 1.0.7.0
