### ISSUE TITLE
Is there any way to scroll unlimitly?

### ISSUE THREAD

**Issue by BoxResin** [alibaba/UltraViewPager#6]
I mean a case that the count of child views is not fixed. Can I scroll `UltraViewPager` in directions both positive and negative unlimitly?

**Comment by MikeAfc** [comment]
I'm not sure if i understand your question correctly, you can just call
ultraViewPager.setInfiniteLoop(true);
to set UltraViewPager scroll unlimitly, and don't forget to call adapter.notifyDataSetChanged() when your child count changed.

**Comment by BoxResin** [comment]
I don't mean 'Loop' feature that scrolls from last to first. The count of view is not 'fixed'. I have N views, and number 'N' increases whenever a user scrolled `ViewPager` to last page. That is, 'N' is infinite.
