### ISSUE TITLE
关于小圆点的问题

### ISSUE THREAD

**Issue by lyy90** [alibaba/UltraViewPager#60]
![screenshot_20170925-114241](https://user-images.githubusercontent.com/5061242/30791756-4757588c-a1e7-11e7-9aff-d036d99cb8c2.png)
集成确定很方便的，但是小圆点位置不好调，

**Comment by MikeAfc** [comment]
可通过 com.tmall.ultraviewpager.IUltraIndicatorBuilder#setMargin 设置小圆点margin，通过com.tmall.ultraviewpager.IUltraIndicatorBuilder#setIndicatorPadding 设置小圆点间距
