### ISSUE TITLE
ultraviewpager 在三星手机一点就崩溃啊

### ISSUE THREAD

**Issue by lyy90** [alibaba/UltraViewPager#66]
![qq 20171020140431](https://user-images.githubusercontent.com/5061242/31807356-3e00317e-b5a0-11e7-8afd-1d00602009c3.png)

**Comment by lyy90** [comment]
三星G9205

**Comment by lyy90** [comment]
我发现所有的手机都会崩溃

**Comment by z2700589** [comment]
不给控件设置adapter的话，都会报这个异常的

**Comment by lyy90** [comment]
我设置的

**Comment by paulwongkwan** [comment]
同樣問題

**Comment by longerian** [comment]
根据设计，初始化的时候需要先设置adapter才行。

**Comment by paulwongkwan** [comment]
初始化的时候已设置adapter了
