### ISSUE TITLE
How to ban sliding

### ISSUE THREAD

**Issue by 7hundeR** [alibaba/UltraViewPager#72]
How to ban sliding

**Comment by longerian** [comment]
call `disableAutoScroll()`

**Comment by 7hundeR** [comment]
Thank you，But,How to ban manual sliding

**Comment by longerian** [comment]
OK, It's developed based on `UltraViewPager`, which is designed for manual silding. So I don't think it's a good idea to ban manual sliding, if you have to do this, you can make it not touchable by yourself.
