### ISSUE TITLE
please fix, NPE @getCurrentItem

### ISSUE THREAD

**Issue by jhlee910609** [alibaba/UltraViewPager#73]
I guess you've already finished NPE in method 'getCurrentItem' in UltraViewPagerView.
but you didn't update for users.
plz update library ver for us!!!

Thanx :)

**Comment by longerian** [comment]
Can you provide the related issue or more detail about NPE?
And do not guess, plz verify it using source code. I will release new version if it was fixed.

**Comment by jhlee910609** [comment]
it's exactly same #48 issue.
I think your team already fix it.
but current library version is not updated from ver 1.0.6.1 to ver 1.0.6.3.
so your work is not affected by code.
please recheck codes #48 issues.

i wish update library version in gradle.
if i miss some point, let me know about it!

**Comment by longerian** [comment]
I have released 1.0.6.4 and it is available on jCenter and mavenCenter

**Comment by jhlee910609** [comment]
oh... I shoud have read README in detail...
Sorry, and Thank you 👍
