### ISSUE TITLE
pagerAdapter使用前未判空

### ISSUE THREAD

**Issue by 127001david** [alibaba/UltraViewPager#74]
onMeasurePage 时使用到 pagerAdapter.getViewAtPosition(getCurrentItem());
按照我的理解在控件绘制前没必要要求把 adapter 设置好的，这样会导致自定义 ViewGroup measureChildren 时 crash。

**Comment by longerian** [comment]
目前的设计是需要初始化的时候设置adapter，先这样适配吧
