### ISSUE TITLE
手动滚动的问题

### ISSUE THREAD

**Issue by gxp3635** [alibaba/UltraViewPager#8]
打开自动滚动后，一直手动向左滑动，会出现滑不动和跳第一页的情况，能否在触摸的时候停止自动滚动。

**Comment by MikeAfc** [comment]
这里分两个问题：
1、滑不动，可通过接口 setInfiniteRatio 将循环次数设到你理想的最大值，原因见 https://github.com/alibaba/UltraViewPager/issues/3；
2、触摸的时候停止自动滚动，UltraViewPager已做处理，代码见com.tmall.ultraviewpager.UltraViewPager#dispatchTouchEvent，确认有问题的话可以沟通我们一起看下；
