### ISSUE TITLE
没法更新数据

### ISSUE THREAD

**Issue by tianyajuechen** [alibaba/UltraViewPager#84]
使用mUltraVpBanner.getViewPager().getAdapter().notifyDataSetChanged();更新数据只有第一次有作用，后面再调用的话只是item数量发生变化。我是刚开始list只有一条数据，notify()正常；后来又刷新了list，变成了两条数据，再调用notify()，发现只是把刚开始加载的那一个item又复制了一份，展示了两个相同的item

**Comment by MikeAfc** [comment]
没大明白意思？数据的变化是？只有一个item，调notifyDataSetChanged没刷新？方便发下使用场景看下？

**Comment by qs-lll** [comment]
没有办法动态更新viewpager的item

在viewpager里是有效的

The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 0, found: 5 Pager id: 1 Pager class: class com.tmall.ultraviewpager.UltraViewPagerView Problematic adapter: class com.tmall.ultraviewpager.UltraViewPagerAdapter

**Comment by MikeAfc** [comment]
Have added method to help refresh data. See faq to learn more:
https://github.com/alibaba/UltraViewPager/wiki/FAQ
https://github.com/alibaba/UltraViewPager#faq
