### ISSUE TITLE
1.setMultiScreen之后setItemMargin失效 2.轮播不支持ViewList的形式，只能每次都去重新生成View

### ISSUE THREAD

**Issue by zjhcode** [alibaba/UltraViewPager#86]
1.setMultiScreen之后setItemMargin失效，那么要怎么实现画廊效果呢，只能在View里面设置padding实现，希望改进。
2.viewpager也可以先把view的list生成好再展示，不用每次在instantiateItem里面new一个view，但是轮播这样写会报错的，建议参考一下，轮播替换view的实现方式，改进这个问题。
3.作为ali的库健壮性偏低，动不动就要报错。

**Comment by MikeAfc** [comment]
1、如你所说，按此实现即可；
2、3、当一个库不符合自己的需求的时候，请考虑自己实现；
开源是分享，不是义务。
