### ISSUE TITLE
就不能提供一个刷新的方法吗？

### ISSUE THREAD

**Issue by zjhcode** [alibaba/UltraViewPager#87]
我想刷新数据
一开始我是这样写的：
ultraViewPager.getAdapter().notifyDataSetChanged()
报错
后来看了源码
改成这样可以了
ultraViewPager.getViewPager().getAdapter().notifyDataSetChanged()

如果说，使用者用你的库，使用一些常用的功能，都不得不看源码才能正常使用，那说明这个封装是失败的呀

**Comment by song314** [comment]
别人至少分享出来了，你觉得失败，你自己试试做一个出来分享给大家呢？

**Comment by MikeAfc** [comment]
Have added method to help refresh data. See faq to learn more:
https://github.com/alibaba/UltraViewPager/wiki/FAQ
https://github.com/alibaba/UltraViewPager#faq
