### ISSUE TITLE
Loading data from local storage?

### ISSUE THREAD

**Issue by aldocano** [alibaba/UltraViewPager#89]
How can i set images to the viewpager from arraylist containing images from local storage?

**Comment by MikeAfc** [comment]
Not understand your question clearly, you can custom your own adapter like com.tmall.ultraviewpager.sample.UltraPagerAdapter, and set your images to viewpager

**Comment by aldocano** [comment]
I have an array containing local urls of the images i need to play, how to set it to the adapter.

**Comment by MikeAfc** [comment]
Extends your adapter from PagerAdapter and do your biz code in instantiateItem method. And if you want more details, google may help you: [https://www.google.com/search?q=viewpager+imageview+url&oq=viewpager+imageview+url&aqs=chrome..69i57j0.4129j0j1&sourceid=chrome&ie=UTF-8](https://www.google.com/search?q=viewpager+imageview+url&oq=viewpager+imageview+url&aqs=chrome..69i57j0.4129j0j1&sourceid=chrome&ie=UTF-8)

**Comment by aldocano** [comment]
What have i done wrong here? 

`

 public class UltraPagerAdapter extends PagerAdapter {
     private Context context;
     private LayoutInflater layoutInflater;
     private ArrayList<String> fotobanner;

    UltraPagerAdapter(Context context, ArrayList<String> arrayList) {
        this.context = context;
        layoutInflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        this.fotobanner = arrayList;
        //notifyDataSetChanged();  

    }

    @Override
    public int getCount() {
            //Log.e ("Size", String.valueOf (fotobanner.get (0)));
            return fotobanner.size();
    }


    @Override
    public boolean isViewFromObject(@NonNull View view, @NonNull Object object) {
        return view == ((LinearLayout) object);
    }

    @NonNull
    @Override
    public Object instantiateItem(@NonNull ViewGroup container, int position) {

        layoutInflater = (LayoutInflater) context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        View view = layoutInflater.inflate(R.layout.item_view,container,false);
        ImageView imageView = view.findViewById(R.id.imageView2);

        //Picasso.get ().load ("https://i.pinimg.com/originals/d5/43/93/d5439328d0afceca5e5d9dea77b72b7b.png").into (imageView);
        Picasso.get().load(new File (Functions.getUnzipLocation(context) +"/"+ fotobanner.get(position))).into(imageView);
        container.addView(view);
        return view;
    }
`
