### ISSUE TITLE
ScrollView inside UltraViewPager

### ISSUE THREAD

**Issue by jemshit** [alibaba/UltraViewPager#92]
Hi, i am using `UltraViewPager` with _Fragments_ inside and _Fragments_ have `ScrollView`. `UltraViewPager` has `scrollMode=VERTICAL`. So i want to be able scroll ScrollView inside UltraViewPager, and after scrollView content is scrolled, UltraViewPager should start scrolling to next page. How do you handle such situation, thanks.

**Comment by defaultbr** [comment]
waiting for something like this, need to change page only when scrollview is in the bottom or top (in my case will be a webview)

**Comment by jemshit** [comment]
implemented this somehow. overrided onTouch of scrollview and
ultaviewpager  . also i had to disable touch event of viewager when
scrollview is in middle so i have forked project and made 2 commits

**Comment by MikeAfc** [comment]
There's no plan for support scrollview inside ultraviewpager, but welcome to commit pull request.
